### ISSUE TITLE
Where to get client_id?

### ISSUE THREAD

**Issue by zhengoogle** [Autodesk-Forge/reality.capture-nodejs-photo.to.3d#5]
{ "developerMessage":"The client_id specified does not have access to the api product","userMessage":"","errorCode":"AUTH-001","more info":"http://developer.api.autodesk.com/documentation/v1/errors/AUTH-001"}

**Comment by jaimerosales** [comment]
Check this post, you might forgot to activate your Trial to give your API keys access to all the services. 
https://forge.autodesk.com/blog/where-are-my-apis
